=== GeniusMachado/XML-Validator/library_DTD.dtd
<!ELEMENT Library (Book|CD_Disk)*>
<!ELEMENT Book (ID|Name|Code|Author|Price|Publication|Type)*>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Code (#PCDATA)>
<!ELEMENT Author (#PCDATA)>
<!ELEMENT Price (#PCDATA)>
<!ELEMENT Publication (#PCDATA)>
<!ELEMENT Type (#PCDATA)>
<!ELEMENT CD_Disk (Type|Size|Name|Version)*>
<!ELEMENT Size (#PCDATA)>
<!ELEMENT Version (#PCDATA)>

=== GeniusMachado/XML-Validator/library.xml
<?xml version="1.0"?>
<!DOCTYPE Library SYSTEM "library_DTD.dtd">
<Library>
  <Book>
      <ID>123</ID>
      <Name>Real Estate Made Easy</Name>
      <Code>1234567890</Code>
      <Author>Grant Cardone</Author>
      <Price>334</Price>
      <Publication>Visual Media</Publication>
      <Type>Novel</Type>
  </Book>
  <CD_Disk>
        <Type>DVD</Type>
        <Size>700MB</Size>
        <Name>Lion Heart</Name>
        <Version>2</Version>
  </CD_Disk>
</Library>
